export const SET_USER = "SET_USER";
export const SET_USER_TYPE = "SET_USER_TYPE";
export const LOGOUT = "LOGOUT";
export const EDIT_USER = "EDIT_USER";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const VALIDATE_REQUEST = "VALIDATE_REQUEST";
export const VALIDATE_SUCCESS = "VALIDATE_SUCCESS";
export const VALIDATE_FAIL = "VALIDATE_FAIL";

export const REGISTER_PROVIDER_REQUEST = "REGISTER_PROVIDER_REQUEST";
export const REGISTER_PROVIDER_SUCCESS = "REGISTER_PROVIDER_SUCCESS";
export const REGISTER_PROVIDER_FAIL = "REGISTER_PROVIDER_FAIL";

export const REGISTER_HELPER_REQUEST = "REGISTER_HELPER_REQUEST";
export const REGISTER_HELPER_SUCCESS = "REGISTER_HELPER_SUCCESS";
export const REGISTER_HELPER_FAIL = "REGISTER_HELPER_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const CONFIRM_EMAIL_REQUEST = "CONFIRM_EMAIL_REQUEST";
export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";
export const CONFIRM_EMAIL_FAIL = "CONFIRM_EMAIL_FAIL";

export const GET_PROVIDERS_REQUEST = "GET_PROVIDERS_REQUEST";
export const GET_PROVIDERS_SUCCESS = "GET_PROVIDERS_SUCCESS";
export const GET_PROVIDERS_FAIL = "GET_PROVIDERS_FAIL";

export const GET_INQUIRIES_REQUEST = "GET_INQUIRIES_REQUEST";
export const GET_INQUIRIES_SUCCESS = "GET_INQUIRIES_SUCCESS";
export const GET_INQUIRIES_FAIL = "GET_INQUIRIES_FAIL";

export const GET_FAVORITES_REQUEST = "GET_FAVORITES_REQUEST";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const GET_FAVORITES_FAIL = "GET_FAVORITES_FAIL";

export const SET_HIGHLIGHTED = "SET_HIGHLIGHTED";
