export { default as Login } from "./Login";
export { default as Map } from "./Map";
export { default as Home } from "./Home";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as BoardingFarmer } from "./BoardingFarmer";
export { default as HelperRegister } from "./HelperRegister";
export { default as ProviderRegister } from "./ProviderRegister";
export { default as SplashScreen } from "./SplashScreen";
export { default as Boarding } from "./Boarding";
