import { ThemeProvider } from "@material-ui/core";
import moment from "moment";
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
import { Router } from "react-router-dom";

import history from "./lib/history";
import { theme } from "./lib/materialUiTheme";
import { initStore } from "./lib/store";
import AppRoutes from "./routes";
import * as serviceWorker from "./serviceWorker";
// Import main css file generated by PostCSS and TailwindCSS
import "./styles/main.css";

const store = initStore();

const render = (Component) => {
  moment.locale("de");
  return ReactDOM.render(
    <Provider store={store}>
      <ThemeProvider theme={theme}>
        <Router history={history}>
          <Component />
        </Router>
      </ThemeProvider>
    </Provider>,
    document.getElementById("root")
  );
};

render(AppRoutes);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
